# Level2 API连接配置文件
# 股票自动交易系统配置

# Level2连接配置
level2:
  # 连接类型: tcp 或 udp
  connection_type: tcp
  
  # TCP连接地址
  tcp_address: "tcp://210.14.72.17:6900"  # 深圳测试桩
  # tcp_address: "tcp://210.14.72.17:16900"  # 上海测试桩 合并流
  # tcp_address: "tcp://210.14.72.17:36900"  # 上海测试桩 非合并流
  
  # UDP组播配置
  multicast_address: "udp://224.224.224.15:7889"
  interface_ip: "10.168.9.46"
  
  # 登录认证信息 (TCP模式需要)
  login_account: "13811112222"  # n-sight.com.cn网站注册手机号
  password: "123456"            # n-sight.com.cn网站登陆密码
  
  # API配置
  cache_mode: false  # 缓存模式，false为非缓存模式，性能更高
  
  # 重连配置
  max_reconnect_attempts: 10  # 最大重连次数
  reconnect_interval: 5       # 重连间隔(秒)
  
  # 订阅配置
  subscriptions:
    # 快照行情订阅
    market_data: true
    securities: 
      - "00000000"  # 全部合约(通配符)
    exchange: "TORA_TSTP_EXD_COMM"  # 全市场
    
    # 逐笔成交订阅 (仅深圳支持)
    transaction: true
    transaction_securities:
      - "300750"    # 深圳股票示例
      - "000001"    # 深圳股票示例
    
    # 逐笔委托订阅 (仅深圳支持)
    order_detail: true
    order_securities:
      - "300750"    # 深圳股票示例
      - "000001"    # 深圳股票示例

# 日志配置
logging:
  level: INFO
  log_dir: "./logs"
  max_file_size: 104857600  # 100MB
  backup_count: 10
  format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"

# 数据处理配置
data_processing:
  batch_size: 100
  batch_timeout: 1.0
  worker_threads: 4
  queue_size: 10000

# 数据库配置
database:
  postgresql:
    host: "localhost"
    port: 5432
    database: "trading_system"
    username: "postgres"
    password: "password"
    pool_size: 10
  
  redis:
    host: "localhost"
    port: 6379
    database: 0
    password: null
    pool_size: 10
  
  influxdb:
    host: "localhost"
    port: 8086
    database: "market_data"
    username: "admin"
    password: "password"

# 性能监控配置
monitoring:
  enable_performance_logging: true
  stats_interval: 60  # 统计信息输出间隔(秒)
  health_check_interval: 30  # 健康检查间隔(秒)
